kind: Deployment
apiVersion: apps/v1
metadata:
   name: myfirstdeployment
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: my-app
   template:
      metadata:
        labels:
          app: my-app
      spec:
       containers:
        - name: my-app
          image: star02/pocreponewpoc-project
          imagePullPolicy: Always
          ports:
          - containerPort: 80
