kind: Service                             
apiVersion: v1
metadata:
  name: myfirstdepployment
  labels:
    app: my-app
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 30000
  selector:
    app: my-app               
  type: LoadBalancer
